services:
  laravel: 
    container_name: wordpress-theme
    build: .
    restart: always
    volumes:
      - ./src:/var/www/html/wp-content/themes/benaus
    ports:
      - 8080:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1